/* Bar functionality */
#include "bar_indicators.h"
#include "bar_tagicons.h"

#include "bar_dwmblocks.h"
#include "bar_ewmhtags.h"
#include "bar_ltsymbol.h"
//#include "bar_status.h"
#include "bar_status2d.h"
#include "bar_statuscmd.h"
#include "bar_tags.h"
#include "bar_wintitle.h"
#include "bar_systray.h"
#include "bar_layoutmenu.h"

/* Other patches */
#include "cfacts.h"
#include "cyclelayouts.h"
#include "dwmc.h"
#include "fakefullscreenclient.h"
#include "focusurgent.h"
#include "movestack.h"
#include "pertag.h"
#include "restartsig.h"
#include "scratchpad.h"
#include "shiftview.h"
#include "shiftviewclients.h"
#include "tapresize.h"
#include "vanitygaps.h"
#include "winview.h"
#include "xrdb.h"
/* Layouts */
#include "layout_bstack.h"
#include "layout_monocle.h"
#include "layout_tile.h"

